Repository perturbo-code/perturbopy, pull requests merged in 2024-12, with the labels that each got.

#73 Fix filtering
  src/perturbopy/test_utils/run_test/run_utils.py
Labels: bug, high priority

#75 Update docs scripts
  docs/perturbo_docs/f90tools.py
  docs/perturbo_docs/htmltools.py
  docs/perturbo_docs/input_parameters.py
  docs/perturbo_docs/interactive_workflow.py
Labels: low priority

#77 Fix bug with the string parameters
  src/perturbopy/generate_input/generate_input.py
Labels: bug

#87 Ultrafast spectroscopy: pump pulse generation
  .gitignore
  docs/perturbo_docs/.gitignore
  docs/perturbo_docs/input_parameters.py
  setup.cfg
  src/perturbopy/postproc/__init__.py
  src/perturbopy/postproc/calc_modes/dyna_run.py
  src/perturbopy/postproc/calc_modes/spectral_cumulant.py
  src/perturbopy/postproc/utils/constants.py
  src/perturbopy/postproc/utils/memory.py
  src/perturbopy/postproc/utils/plot_tools.py
  src/perturbopy/postproc/utils/spectra_generate_pulse.py
  src/perturbopy/postproc/utils/spectra_plots.py
  src/perturbopy/postproc/utils/timing.py
  src/perturbopy/test_utils/compare_data/h5.py
  src/perturbopy/test_utils/compare_data/yaml.py
  src/perturbopy/yml_files/files_description.yml
  src/perturbopy/yml_files/input_parameters_perturbo.yml
  src/perturbopy/yml_files/input_template.yml
  src/perturbopy/yml_files/workflow.yml
  tests/test_constants.py
Labels: enhancement, high priority

#91 Transient absorption calculation and plotting
  setup.cfg
  src/perturbopy/postproc/__init__.py
  src/perturbopy/postproc/calc_modes/dyna_run.py
  src/perturbopy/postproc/dbs/units_dict.py
  src/perturbopy/postproc/utils/spectra_generate_pulse.py
  src/perturbopy/postproc/utils/spectra_plots.py
  src/perturbopy/postproc/utils/spectra_trans_abs.py
Labels: enhancement
